// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

import 'package:firebase_core/firebase_core.dart';

// ...

// await Firebase.initializeApp(
//     options: DefaultFirebaseOptions.currentPlatform,
// );

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhnJnW0oJZrkuob2qZ0Dj0nVRu6xnozNI',
    appId: '1:740320757439:web:5ea5c49a2897f15fef680a',
    messagingSenderId: '740320757439',
    projectId: 'bookclub-ec259',
    authDomain: 'bookclub-ec259.firebaseapp.com',
    storageBucket: 'bookclub-ec259.appspot.com',
    measurementId: 'G-ZJZMBPDFYS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAV9P-yNlbDKbumsNemz9_NeJSbFYBKvbI',
    appId: '1:740320757439:android:2d68d176a15b3185ef680a',
    messagingSenderId: '740320757439',
    projectId: 'bookclub-ec259',
    storageBucket: 'bookclub-ec259.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEpbXsVpcDg687XgKdcUBAwDpFK3vhj98',
    appId: '1:740320757439:ios:3a7d3bd10b994f10ef680a',
    messagingSenderId: '740320757439',
    projectId: 'bookclub-ec259',
    storageBucket: 'bookclub-ec259.appspot.com',
    iosBundleId: 'com.example.bookClub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEpbXsVpcDg687XgKdcUBAwDpFK3vhj98',
    appId: '1:740320757439:ios:05fc19d3ae47cc1bef680a',
    messagingSenderId: '740320757439',
    projectId: 'bookclub-ec259',
    storageBucket: 'bookclub-ec259.appspot.com',
    iosBundleId: 'com.example.bookClub.RunnerTests',
  );
}
